### ISSUE TITLE
Request External Review Of Project Set Up

### ISSUE THREAD

**Issue by oluyaratosin123** [oluyaratosin123/Space-Travellers#24]
This project was built solo and that was because my partner had some Issue which I have finally addressed with student success, And I was told to do this project solo this week

- I have assign all projects to my self in this repository [issue](https://github.com/oluyaratosin123/Space-Travellers/issues)
- I have also create the project for this [app](https://github.com/oluyaratosin123/Space-Travellers/projects/1)

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @oluyaratosin123,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
